<script setup>
import { computed, onMounted, ref } from 'vue'
import Button from 'primevue/button'; import Dialog from 'primevue/dialog'; import Select from 'primevue/select'; import DatePicker from 'primevue/datepicker'; import Message from 'primevue/message'; import ConfirmDialog from 'primevue/confirmdialog'; import { useConfirm } from 'primevue/useconfirm'
import StatusTag from '../../components/StatusTag.vue'; import LoadingState from '../../components/LoadingState.vue'; import EmptyState from '../../components/EmptyState.vue'; import api,{errorMessage} from '../../services/api'; import {formatDate,formatTime,labelFor} from '../../utils/status'
const confirm=useConfirm(), facilities=ref([]), bookings=ref([]), loading=ref(true), error=ref(''), dialog=ref(false), saving=ref(false), formError=ref(''); const form=ref({facilityId:null,startTime:null,endTime:null})
const bookable = computed(()=>facilities.value.filter(f=>f.active&&f.bookable&&f.status==='AVAILABLE')); const icon=(type)=>({GYM:'pi pi-heart',BADMINTON_COURT:'pi pi-circle',COMMUNITY_ROOM:'pi pi-users',READING_ROOM:'pi pi-book',MEETING_ROOM:'pi pi-comments'}[type]||'pi pi-th-large')
const localDateTime=(value)=>{const d=new Date(value);const p=(n)=>String(n).padStart(2,'0');return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}T${p(d.getHours())}:${p(d.getMinutes())}:00`}
const load=async()=>{loading.value=true;error.value='';try{const [f,b]=await Promise.all([api.get('/facilities'),api.get('/bookings/my')]);facilities.value=f.data;bookings.value=b.data}catch(e){error.value=errorMessage(e)}finally{loading.value=false}}
const openDialog=(facility=null)=>{form.value={facilityId:facility?.id||null,startTime:null,endTime:null};formError.value='';dialog.value=true}
const submit=async()=>{formError.value='';if(!form.value.facilityId||!form.value.startTime||!form.value.endTime){formError.value='Vui lòng chọn tiện ích và thời gian.';return}if(form.value.startTime>=form.value.endTime){formError.value='Thời gian kết thúc phải sau thời gian bắt đầu.';return}saving.value=true;try{await api.post('/bookings',{facilityId:form.value.facilityId,startTime:localDateTime(form.value.startTime),endTime:localDateTime(form.value.endTime)});dialog.value=false;await load()}catch(e){formError.value=errorMessage(e)}finally{saving.value=false}}
const cancel=(booking)=>confirm.require({message:`Hủy lịch đặt ${booking.code}?`,header:'Hủy lịch đặt',acceptLabel:'Hủy lịch',accept:async()=>{try{await api.patch(`/bookings/${booking.id}/cancel`);await load()}catch(e){error.value=errorMessage(e)}}})
onMounted(load)
</script>
<template><div class="page-heading"><div><h1>Đặt tiện ích</h1><p>Chọn không gian phù hợp cho sinh hoạt của bạn.</p></div><Button label="Đặt tiện ích" icon="pi pi-plus" @click="openDialog()" /></div><LoadingState v-if="loading" /><div v-else-if="error" class="error-panel">{{error}}</div><template v-else><section><h2 class="section-title">Tiện ích sẵn sàng</h2><EmptyState v-if="!facilities.length" title="Chưa có tiện ích" /><div v-else class="facility-grid"><article v-for="facility in facilities" :key="facility.id" class="facility-card"><div class="facility-top"><span class="facility-icon"><i :class="icon(facility.type)" /></span><StatusTag :value="facility.status" /></div><h3>{{facility.name}}</h3><span class="muted">{{labelFor(facility.type)}}</span><div class="card-meta"><span><i class="pi pi-clock" /> {{formatTime(facility.openingTime)}} – {{formatTime(facility.closingTime)}}</span><span><i class="pi pi-building" /> {{facility.buildingId ? `Tòa nhà #${facility.buildingId}` : 'Khu cộng đồng'}}</span></div><Button :label="facility.bookable&&facility.status==='AVAILABLE'&&facility.active?'Đặt lịch':'Chưa thể đặt'" :disabled="!facility.bookable||facility.status!=='AVAILABLE'||!facility.active" outlined fluid @click="openDialog(facility)" /></article></div></section><section><h2 class="section-title">Lịch đặt của tôi</h2><EmptyState v-if="!bookings.length" title="Chưa có lịch đặt" /><div v-else class="visitor-grid"><article v-for="booking in bookings" :key="booking.id" class="visitor-card"><div class="visitor-top"><strong class="code">{{booking.code}}</strong><StatusTag :value="booking.status" /></div><h3>{{booking.facilityName}}</h3><div class="card-meta"><span><i class="pi pi-calendar" /> {{formatDate(booking.startTime)}}</span><span><i class="pi pi-clock" /> {{formatDate(booking.endTime)}}</span></div><div class="card-actions"><Button v-if="booking.status==='CONFIRMED'&&new Date(booking.startTime)>new Date()" label="Hủy lịch" severity="danger" text @click="cancel(booking)" /></div></article></div></section></template><Dialog v-model:visible="dialog" modal header="Đặt tiện ích" :style="{width:'min(38rem,94vw)'}"><Message v-if="formError" severity="error">{{formError}}</Message><div class="form-grid"><div class="field full"><label>Tiện ích</label><Select v-model="form.facilityId" :options="bookable" option-label="name" option-value="id" placeholder="Chọn tiện ích" /></div><div class="field"><label>Bắt đầu</label><DatePicker v-model="form.startTime" show-time hour-format="24" :min-date="new Date()" /></div><div class="field"><label>Kết thúc</label><DatePicker v-model="form.endTime" show-time hour-format="24" :min-date="new Date()" /></div></div><p class="muted">Hệ thống sẽ kiểm tra giờ mở cửa và lịch trùng trước khi xác nhận.</p><div class="dialog-footer"><Button label="Hủy" text @click="dialog=false" /><Button label="Xác nhận đặt" :loading="saving" @click="submit" /></div></Dialog></template>
