<script setup>
import { computed, onMounted, ref } from 'vue'
import Chart from 'primevue/chart'
import LoadingState from '../../components/LoadingState.vue'
import PageHeader from '../../components/PageHeader.vue'
import StatCard from '../../components/StatCard.vue'
import api, { errorMessage } from '../../services/api'
import { auditDescription, formatDate, labelFor } from '../../utils/status'
const data = ref(null); const error = ref('')
const chartOptions = { plugins: { legend: { position: 'bottom' } }, maintainAspectRatio: false }
const statusChart = computed(() => !data.value ? null : ({ labels: ['Mới tiếp nhận', 'Đã phân công', 'Đang xử lý', 'Chờ xác nhận', 'Hoàn thành'], datasets: [{ data: [data.value.serviceRequests.open, data.value.serviceRequests.assigned, data.value.serviceRequests.inProgress, data.value.serviceRequests.resolved, data.value.serviceRequests.closed], backgroundColor: ['#60a5fa', '#fbbf24', '#f97316', '#34d399', '#14b8a6'], borderWidth: 0 }] }))
const categoryChart = computed(() => !data.value ? null : ({ labels: Object.keys(data.value.serviceRequests.requestsByCategory || {}).map(labelFor), datasets: [{ label: 'Yêu cầu', data: Object.values(data.value.serviceRequests.requestsByCategory || {}), backgroundColor: '#0f766e', borderRadius: 6 }] }))
const load = async () => { try { data.value = (await api.get('/management/dashboard')).data } catch (e) { error.value = errorMessage(e) } }
onMounted(load)
</script>
<template><PageHeader title="Tổng quan vận hành" description="Những việc cần ưu tiên trong cộng đồng hôm nay." /><div v-if="error" class="error-panel">{{ error }}</div><LoadingState v-else-if="!data" /><template v-else><section class="kpi-grid"><StatCard label="Yêu cầu mới" :value="data.serviceRequests.open" icon="pi pi-inbox" tone="blue" to="/manager/requests" hint="Cần tiếp nhận" /><StatCard label="Chưa phân công" :value="data.serviceRequests.open" icon="pi pi-user-plus" tone="amber" to="/manager/requests?view=assignment" hint="Chọn kỹ thuật viên" /><StatCard label="Đang xử lý" :value="data.serviceRequests.inProgress" icon="pi pi-cog" tone="teal" to="/manager/requests" /><StatCard label="Đã quá hạn xử lý" :value="data.serviceRequests.overdue" icon="pi pi-exclamation-triangle" tone="rose" to="/manager/requests" hint="Cần theo dõi" /><StatCard label="Lịch đặt hôm nay" :value="data.bookings.today" icon="pi pi-calendar" tone="violet" to="/manager/bookings" /><StatCard label="Khách trong khu" :value="data.visitors.checkedIn" icon="pi pi-users" tone="teal" /></section><section class="dashboard-grid"><article class="content-card"><div class="section-heading"><div><p class="eyebrow">Theo dõi yêu cầu</p><h2>Trạng thái xử lý</h2></div><RouterLink to="/manager/requests">Xem yêu cầu</RouterLink></div><div class="chart-wrap"><Chart type="doughnut" :data="statusChart" :options="chartOptions" /></div></article><article class="content-card"><div class="section-heading"><div><p class="eyebrow">Xu hướng</p><h2>Yêu cầu theo nhóm</h2></div></div><div class="chart-wrap"><Chart type="bar" :data="categoryChart" :options="chartOptions" /></div></article></section><section class="dashboard-grid"><article class="content-card"><div class="section-heading"><div><p class="eyebrow">Hoạt động mới</p><h2>Nhật ký gần đây</h2></div><RouterLink to="/manager/audit">Xem tất cả</RouterLink></div><div v-if="!data.recentActivity?.length" class="muted empty-inline">Chưa có hoạt động vận hành gần đây.</div><div v-else class="activity-list"><div v-for="item in data.recentActivity" :key="`${item.entityType}-${item.entityId}-${item.timestamp}`" class="activity"><strong>{{ labelFor(item.action) }}</strong><small>{{ item.actorFullName || 'Hệ thống' }} · {{ auditDescription(item.action, item.description) }} · {{ formatDate(item.timestamp) }}</small></div></div></article><article class="content-card"><p class="eyebrow">Tình hình cộng đồng</p><h2 class="section-title">Chỉ số nhanh</h2><div class="card-meta"><span><i class="pi pi-users" /> {{ data.residents.active }} cư dân đang hoạt động</span><span><i class="pi pi-th-large" /> {{ data.facilities.available }}/{{ data.facilities.total }} tiện ích có thể sử dụng</span><span><i class="pi pi-clock" /> Trung bình {{ data.serviceRequests.averageResolutionMinutes }} phút xử lý</span></div></article></section></template></template>
